#!/usr/bin/env bash
# Runtime setup: install lagh into its venv (editable, from the mounted source), then
# write the Hermes config (MiniMax model + lagh MCP server) if it isn't there yet.
# Idempotent -- safe to re-run on every container start.
set -euo pipefail

LAGH_SRC="${LAGH_SRC:-/opt/lagh}"
LAGH_PY="/opt/lagh-venv/bin/python"
HERMES_CFG="${HERMES_CFG:-/root/.hermes/config.yaml}"

# 1) lagh (+ the mcp extra) into its isolated venv, editable so host edits reflect live
if [ -f "${LAGH_SRC}/pyproject.toml" ]; then
    # reinstall if either the mcp OR the lab subpackage is missing (a warm venv from an
    # older image may predate lagh.lab)
    if ! "${LAGH_PY}" -c "import lagh.mcp, lagh.lab" 2>/dev/null; then
        echo "[entrypoint] installing lagh[mcp] (editable) from ${LAGH_SRC} ..."
        "${LAGH_PY}" -m pip install -q --upgrade pip
        "${LAGH_PY}" -m pip install -q -e "${LAGH_SRC}[mcp]"
    fi
    # the `newtonbench` lab source imports NewtonBench's eval chain (openai, requests, ...)
    # at module load; install its deps when NewtonBench is mounted so the source can load
    NB_DIR="${NEWTONBENCH_DIR:-/opt/NewtonBench}"
    if [ -d "${NB_DIR}" ] && ! "${LAGH_PY}" -c "import openai, requests" 2>/dev/null; then
        echo "[entrypoint] installing newtonbench source deps (openai, requests, its requirements) ..."
        [ -f "${NB_DIR}/requirements.txt" ] && "${LAGH_PY}" -m pip install -q -r "${NB_DIR}/requirements.txt" || true
        "${LAGH_PY}" -m pip install -q openai requests
    fi
    echo "[entrypoint] lagh ready: $("${LAGH_PY}" -c 'import lagh; print(lagh.__version__)')"
else
    echo "[entrypoint] WARNING: no lagh source at ${LAGH_SRC} (mount it in docker-compose)."
fi

# 2) Hermes config: MiniMax as a custom OpenAI-compatible provider + lagh MCP server.
#    The API key is NOT written here -- `key_env` tells Hermes to read it from the
#    container env (compose injects LLM_API_KEY from your .env).
mkdir -p "$(dirname "${HERMES_CFG}")"
# ALWAYS regenerate from the current env, so a `.env` change + `up -d --build` takes
# effect (the old skip-if-exists guard cached a stale config in the volume). If you
# hand-edit the config, set HERMES_KEEP_CONFIG=1 to preserve it.
if [ "${HERMES_KEEP_CONFIG:-0}" != "1" ] || [ ! -f "${HERMES_CFG}" ]; then
    echo "[entrypoint] (re)writing Hermes config from env -> ${HERMES_CFG}"
    cat > "${HERMES_CFG}" <<YAML
# generated by deploy/hermes/entrypoint.sh -- edit freely, it won't be overwritten
# once it mentions 'lagh'. See deploy/hermes/README.md for the adjustment points.
# MiniMax exposes an ANTHROPIC-compatible endpoint (path /anthropic), so this is a
# custom provider in anthropic_messages wire mode -- NOT provider: anthropic (that only
# targets api.anthropic.com) and NOT the OpenAI chat dialect. Key inlined from env.
custom_providers:
  - name: minimax
    base_url: "${LLM_BASE_URL:-https://api.minimax.io/anthropic}"
    api_key: "${LLM_API_KEY}"
    api_mode: anthropic_messages

model:
  default: "${LLM_MODEL:-MiniMax-M3}"
  provider: custom:minimax

mcp_servers:
  lagh:
    command: "${LAGH_PY}"
    args: ["-m", "lagh.mcp.server"]
    # recover/verify/fit -- certified law discovery
  lab:
    command: "${LAGH_PY}"
    args: ["-m", "lagh.lab.server"]
    # Hermes spawns MCP servers with a controlled env, so the lab source + NewtonBench
    # path must be passed EXPLICITLY here (container env does NOT propagate through).
    env:
      LAB_SOURCE: "${LAB_SOURCE:-proxy}"
      NEWTONBENCH_DIR: "${NEWTONBENCH_DIR:-/opt/NewtonBench}"
YAML
else
    echo "[entrypoint] Hermes config already present (${HERMES_CFG}); leaving it."
fi

if [ -z "${LLM_API_KEY:-}" ]; then
    echo "[entrypoint] NOTE: LLM_API_KEY is empty -- set it in deploy/hermes/.env before running Hermes."
fi

echo "[entrypoint] ready. Run:  docker compose exec -it hermes hermes"
exec "$@"
