#!/usr/bin/env bash
# Runtime setup: install lagh into its venv (editable, from the mounted source), then
# write the Hermes config (MiniMax model + lagh MCP server) if it isn't there yet.
# Idempotent -- safe to re-run on every container start.
set -euo pipefail

LAGH_SRC="${LAGH_SRC:-/opt/lagh}"
LAGH_PY="/opt/lagh-venv/bin/python"
HERMES_CFG="${HERMES_CFG:-/root/.hermes/config.yaml}"

# 1) lagh (+ the mcp extra) into its isolated venv, editable so host edits reflect live
if [ -f "${LAGH_SRC}/pyproject.toml" ]; then
    if ! "${LAGH_PY}" -c "import lagh.mcp" 2>/dev/null; then
        echo "[entrypoint] installing lagh[mcp] (editable) from ${LAGH_SRC} ..."
        "${LAGH_PY}" -m pip install -q --upgrade pip
        "${LAGH_PY}" -m pip install -q -e "${LAGH_SRC}[mcp]"
    fi
    echo "[entrypoint] lagh ready: $("${LAGH_PY}" -c 'import lagh; print(lagh.__version__)')"
else
    echo "[entrypoint] WARNING: no lagh source at ${LAGH_SRC} (mount it in docker-compose)."
fi

# 2) Hermes config: MiniMax as a custom OpenAI-compatible provider + lagh MCP server.
#    The API key is NOT written here -- `key_env` tells Hermes to read it from the
#    container env (compose injects LLM_API_KEY from your .env).
mkdir -p "$(dirname "${HERMES_CFG}")"
if [ ! -f "${HERMES_CFG}" ] || ! grep -q "lagh" "${HERMES_CFG}" 2>/dev/null; then
    echo "[entrypoint] writing Hermes config -> ${HERMES_CFG}"
    cat > "${HERMES_CFG}" <<YAML
# generated by deploy/hermes/entrypoint.sh -- edit freely, it won't be overwritten
# once it mentions 'lagh'. See deploy/hermes/README.md for the adjustment points.
model:
  default: "${LLM_MODEL:-MiniMax-M3}"
  provider: custom
  base_url: "${LLM_BASE_URL:-https://api.minimax.io/v1}"
  api_key: "${LLM_API_KEY}"     # inlined from the container env (key_env wasn't honored
                                # by this Hermes build; the file lives only in the local volume)

mcp_servers:
  lagh:
    command: "${LAGH_PY}"
    args: ["-m", "lagh.mcp.server"]
    # recover/verify/fit -- certified law discovery
YAML
else
    echo "[entrypoint] Hermes config already present (${HERMES_CFG}); leaving it."
fi

if [ -z "${LLM_API_KEY:-}" ]; then
    echo "[entrypoint] NOTE: LLM_API_KEY is empty -- set it in deploy/hermes/.env before running Hermes."
fi

echo "[entrypoint] ready. Run:  docker compose exec -it hermes hermes"
exec "$@"
