#!/usr/bin/env python3
"""Generate Hermes config.yaml from env -- provider-agnostic, so the SAME harness runs
on any backing model by editing .env only.

    LLM_MODEL          model id                (e.g. MiniMax-M3, grok-4.5, gpt-6)
    LLM_BASE_URL       OpenAI/Anthropic-compatible root
    LLM_API_KEY        the key (inlined; the file lives only in the local volume)
    LLM_API_MODE       'anthropic_messages' for an /anthropic endpoint; EMPTY for the
                       OpenAI Chat dialect (Grok/xAI, OpenAI) -- omitted when empty
    LLM_PROVIDER_NAME  custom provider name (default 'model')
    LAB_SOURCE / NEWTONBENCH_DIR   passed to the lab MCP server's env
    LAGH_PY            python that runs the MCP servers (default /opt/lagh-venv/bin/python)
    HERMES_CFG         output path (default ~/.hermes/config.yaml)
"""
import os

key = os.environ.get("LLM_API_KEY", "")
model = os.environ.get("LLM_MODEL", "")
base = os.environ.get("LLM_BASE_URL", "")
mode = os.environ.get("LLM_API_MODE", "").strip()          # anthropic_messages | '' (openai)
name = os.environ.get("LLM_PROVIDER_NAME", "model").strip() or "model"
labsrc = os.environ.get("LAB_SOURCE", "proxy")
nbdir = os.environ.get("NEWTONBENCH_DIR", "/opt/NewtonBench")
lagh_py = os.environ.get("LAGH_PY", "/opt/lagh-venv/bin/python")
cfg_path = os.path.expanduser(os.environ.get("HERMES_CFG", "~/.hermes/config.yaml"))

prov = [f"  - name: {name}", f"    base_url: {base}", f'    api_key: "{key}"']
if mode:                                                    # OpenAI dialect => omit api_mode
    prov.append(f"    api_mode: {mode}")

cfg = ("# generated by deploy/hermes/gen_config.py from env -- edit .env + `up -d`, or set\n"
       "# HERMES_KEEP_CONFIG=1 to hand-edit. Provider-agnostic: swap models via LLM_* vars.\n"
       "custom_providers:\n" + "\n".join(prov) + f"""

model:
  default: "{model}"
  provider: custom:{name}

mcp_servers:
  lagh:
    command: {lagh_py}
    args: ["-m", "lagh.mcp.server"]
  lab:
    command: {lagh_py}
    args: ["-m", "lagh.lab.server"]
    env:
      LAB_SOURCE: "{labsrc}"
      NEWTONBENCH_DIR: "{nbdir}"
""")

os.makedirs(os.path.dirname(cfg_path), exist_ok=True)
open(cfg_path, "w").write(cfg)
print(f"[gen_config] provider={name} model={model!r} base={base} "
      f"api_mode={mode or '(openai default)'} lab={labsrc} -> {cfg_path}")
